// Datos de ejemplo — misma forma exacta que devuelve el endpoint real (BRIEF §3.2,
// actualizado tras la reforma de agosto 2026 al sistema de cargas de donaciones).
// Fase 1 del plan de construcción: esqueleto estático, sin fetch todavía.
// Fase 2 reemplaza el consumo de EXAMPLE_DATA por la respuesta real de api.js.
const EXAMPLE_DATA = {
  recaudado: 6963287,
  recibido_en_especie: 5000,
  utilizado: 1064622,
  saldo: 5898665,
  donaciones: 8,
  gastos: 6,
  entregas: 0,
  beneficiarios: 2,
  beneficiarios_mujeres: 1,
  beneficiarios_infancias: 1,
  beneficiarios_diversidades: 0,
  beneficiarios_varones: 0,
  animales_beneficiados: 1,
  ultima_actualizacion: "2026-08-23",
  generado: "2026-08-23T20:28:09.262Z",
  operaciones: [
    { id: "ING-0001", fecha: "2026-08-10", tipo: "INGRESO", categoria: "-", concepto: "Donación colecta comunitaria - Red Ambientales", importe: 1095000, comprobante: "https://drive.google.com/comprobante-ing-01", tipo_recurso: "MONETARIO" },
    { id: "ING-0002", fecha: "2026-08-11", tipo: "INGRESO", categoria: "-", concepto: "Aporte solidario - egresados UTP", importe: 850000, comprobante: "", tipo_recurso: "MONETARIO" },
    { id: "ING-0003", fecha: "2026-08-12", tipo: "INGRESO", categoria: "-", concepto: "Donación campaña redes sociales", importe: 2100000, comprobante: "https://drive.google.com/comprobante-ing-03", tipo_recurso: "MONETARIO" },
    { id: "ING-0004", fecha: "2026-08-13", tipo: "INGRESO", categoria: "-", concepto: "Aporte aliado institucional", importe: 1800000, comprobante: "https://drive.google.com/comprobante-ing-04", tipo_recurso: "MONETARIO" },
    { id: "ING-0005", fecha: "2026-08-14", tipo: "INGRESO", categoria: "-", concepto: "Donación colecta comunitaria", importe: 613287, comprobante: "", tipo_recurso: "MONETARIO" },
    { id: "ING-0006", fecha: "2026-08-15", tipo: "INGRESO", categoria: "-", concepto: "Aporte solidario", importe: 350000, comprobante: "https://drive.google.com/comprobante-ing-06", tipo_recurso: "MONETARIO" },
    { id: "ING-0007", fecha: "2026-08-16", tipo: "INGRESO", categoria: "-", concepto: "Donación campaña redes sociales", importe: 155000, comprobante: "", tipo_recurso: "MONETARIO" },
    { id: "ING-0008", fecha: "2026-08-19", tipo: "INGRESO", categoria: "-", concepto: "harina", importe: 5000, comprobante: "", tipo_recurso: "ESPECIE" },
    { id: "EGR-0001", fecha: "2026-08-11", tipo: "EGRESO", categoria: "COMUNICACION", concepto: "Difusión y diseño de piezas de campaña", importe: 14000, comprobante: "https://drive.google.com/comprobante-egr-01", tipo_recurso: "-" },
    { id: "EGR-0002", fecha: "2026-08-12", tipo: "EGRESO", categoria: "ALIMENTOS", concepto: "Compra de alimentos no perecederos - proveedor local", importe: 420000, comprobante: "https://drive.google.com/comprobante-egr-02", tipo_recurso: "-" },
    { id: "EGR-0003", fecha: "2026-08-13", tipo: "EGRESO", categoria: "LOGISTICA", concepto: "Alquiler de vehículo para traslado de insumos", importe: 280000, comprobante: "https://drive.google.com/comprobante-egr-03", tipo_recurso: "-" },
    { id: "EGR-0004", fecha: "2026-08-14", tipo: "EGRESO", categoria: "INSUMOS/EQUIPAMIENTO", concepto: "Kits de higiene y salud básica", importe: 180622, comprobante: "", tipo_recurso: "-" },
    { id: "EGR-0005", fecha: "2026-08-15", tipo: "EGRESO", categoria: "TRANSPORTE", concepto: "Combustible para nodo Chocó y Risaralda", importe: 95000, comprobante: "https://drive.google.com/comprobante-egr-05", tipo_recurso: "-" },
    { id: "EGR-0006", fecha: "2026-08-16", tipo: "EGRESO", categoria: "ALIMENTOS", concepto: "Olla comunitaria Las Weras - insumos", importe: 75000, comprobante: "https://drive.google.com/comprobante-egr-06", tipo_recurso: "-" },
  ],
  entregas_detalle: [],
  impacto_por_categoria: [
    { categoria: "ALIMENTOS", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
    { categoria: "AGUA", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
    { categoria: "MEDICAMENTOS", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
    { categoria: "INSUMOS/EQUIPAMIENTO", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
    { categoria: "TRANSPORTE", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
    { categoria: "LOGISTICA", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
    { categoria: "ALOJAMIENTO TEMPORAL", mujeres: 1, infancias: 1, diversidades: 0, varones: 0, animales: 1, total_personas: 2 },
    { categoria: "COMUNICACION", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
    { categoria: "AYUDA ECONOMICA DIRECTA", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
    { categoria: "ROPA", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
    { categoria: "PAP APOYO EMOCIONAL", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
    { categoria: "OTROS", mujeres: 0, infancias: 0, diversidades: 0, varones: 0, animales: 0, total_personas: 0 },
  ],
};
