// Roster de responsables — contenido propio de la landing, no viene del endpoint (BRIEF §2.3).
const RESPONSABLES = [
  {
    nombre: "Johan Toro",
    rol: "Coordinación general — Logística de Asistencia y Albergue",
    ubicacion: "México",
    foto: "assets/responsables/johan-toro.png",
    bio: "Especialista en Gestión Integral de Riesgos y Resiliencia Urbana, Administrador Ambiental, Maestro en Población y Desarrollo por FLACSO México y candidato a Doctor en Estudios de Población por El Colegio de México, con una trayectoria enfocada en vulnerabilidad social, construcción social del riesgo, territorio y resiliencia. Es fundador y director operativo de Genera Territorios A.C., organización orientada al fortalecimiento de capacidades y la articulación de iniciativas para el desarrollo territorial sostenible, la autonomía económica y la regeneración socioambiental. Su experiencia combina investigación aplicada, análisis territorial y diseño de instrumentos para la reducción del riesgo y la resiliencia. Actualmente se desempeña como Coordinador de Políticas de Resiliencia de la Ciudad de México.",
  },
  {
    nombre: "Francisco Gallo",
    rol: "Soluciones basadas en naturaleza y restauración ecológica",
    ubicacion: "Pereira",
    foto: "assets/responsables/francisco-gallo.png",
    bio: "Administrador Ambiental, Explorador de National Geographic y Dr. Arquitecto (Cum Laude) por la Euskal Herriko Unibertsitatea. Con suficiencia investigadora en Asentamientos Humanos y Actividades Económicas (doctorado en Geografía e Historia-UNED); Magíster en Cooperación Internacional para el Desarrollo en el Sistema de Naciones Unidas (2006-7). Por más de 20 años ha implementado soluciones basadas en naturaleza y restauración ecológica.",
  },
  {
    nombre: "Margarita Noreña",
    rol: "Coordinación de Logística / Salud Pública y Asistencia Integral",
    ubicacion: "Pereira",
    foto: "assets/responsables/margarita-norena.png",
    bio: "Administradora Ambiental de la Universidad Tecnológica de Pereira, especialista en Análisis de Política Pública y magíster en Estudios Culturales y Narrativas Contemporáneas. Su trayectoria está vinculada a la gestión de proyectos ambientales y sociales, el trabajo con comunidades y la articulación entre territorios, instituciones, academia y organizaciones.",
  },
  {
    nombre: "Sara Arenas",
    rol: "Coordinación de Logística / Nodo Chocó y Risaralda",
    ubicacion: "Pereira",
    foto: "assets/responsables/sara-arenas.png",
    bio: "El enfoque principal en mi proceso profesional ha sido orientado como investigadora y gestora, especialmente en el sector rural, comunitario y académico desde la aproximación cultural e interdisciplinaria al reconocimiento de los procesos ambientales. Como gestora de procesos de desarrollo, he sido parte de procesos de planificación ambiental y divulgación del conocimiento para fortalecer la concepción del ambiente y el territorio como un patrimonio y un derecho social. Actualmente, soy docente acompañante en el pregrado de Administración Ambiental de la Universidad Tecnológica de Pereira, en la Alcaldía de San José, Caldas, y me encuentro finalizando mis estudios de maestría en Gestión del Riesgo de Desastres, los cuales he enfocado en los conflictos de gestión del riesgo en la comunidad de Carmelo, Chocó.",
  },
  {
    nombre: "Stefanía Giraldo",
    rol: "Coordinación de Logística",
    ubicacion: "Pereira",
    foto: "assets/responsables/stefania-giraldo.png",
    bio: "Administradora Ambiental y Especialista en Prevención, Reducción y Atención de Desastres, con 7 años de experiencia en gestión del riesgo de desastres en entidades de orden municipal y nacional. Aporta elementos técnicos y experiencia en gestión del riesgo, y es enlace entre la institucionalidad y la comunidad.",
  },
  {
    nombre: "Luciana González",
    rol: "Nodo Pereira — Olla Comunitaria Las Weras",
    ubicacion: "Pereira",
    foto: "assets/responsables/luciana-gonzalez.png",
    bio: "Administradora Ambiental. Gestión ambiental, proyectos y trabajo comunitario para la vida y los territorios. En Ambientales por la Vida construyo puentes entre la academia y la comunidad, integrando gestión ambiental, capacidad organizativa y trabajo colectivo para fortalecer territorios y promover soluciones sostenibles.",
  },
  { nombre: "Andrés Cardona", rol: "Nodo Norte del Valle y Pereira", ubicacion: "Cartago", foto: "assets/responsables/andres-cardona.png" },
  {
    nombre: "Marta Ochoa",
    rol: "Articulación interinstitucional y comunitaria / EDAN",
    ubicacion: "Bogotá",
    foto: "assets/responsables/marta-ochoa.png",
    bio: "Administradora Ambiental y especialista en gestión ambiental de la Universidad Tecnológica de Pereira, con estudios en mercados y políticas de suelo y candidata a magíster en Estudios Críticos de las Migraciones Contemporáneas de la Pontificia Universidad Javeriana. Durante más de 18 años su experiencia profesional ha estado focalizada en la gestión del riesgo de desastres y la adaptación al cambio climático en entidades del orden nacional, donde ha contribuido a la formulación de políticas públicas e instrumentos de gestión del riesgo y de adaptación al cambio climático, como el Plan Nacional de Gestión del Riesgo de Desastres 2015-2025, adoptado por Decreto 308 de 2016.",
  },
  {
    nombre: "Paula Ramírez",
    rol: "Salud Mental y Apoyo Psicosocial (SMAPS)",
    ubicacion: "Argentina",
    foto: "assets/responsables/paula-ramirez.png",
    bio: "Administradora Ambiental y Especialista en Gestión Ambiental (UTP). Candidata a magíster en Desarrollo Sustentable UNLu–FLACAM. Radicada en Argentina. Tiene experiencia en gestión pública y proyectos estratégicos de sustentabilidad, gestión hídrica, cambio climático y desarrollo territorial, con foco en gestión del agua, riesgo hídrico, restauración fluvial, participación comunitaria e incorporación de la perspectiva de género. Es promotora activa de la igualdad de género y la sustentabilidad ambiental, vinculada a redes como Mujeres en Diálogo Ambiental y el Movimiento Basura Cero en Argentina.",
  },
  {
    nombre: "Mario Arenas",
    rol: "Sistematización de proveedores locales",
    ubicacion: "Pereira",
    foto: "assets/responsables/mario-arenas.png",
    bio: "Administrador del Medio Ambiente, Especialista en Gestión Ambiental Local y Magíster en Desarrollo Regional y Planificación del Territorio. Mi experiencia se concentra en planificación urbana y regional, ordenamiento territorial, gestión ambiental, movilidad activa y sostenible, acción climática, y formulación de proyectos y políticas públicas. He trabajado con entidades públicas, academia, cooperación y organizaciones ciudadanas, articulando conocimiento técnico, gestión y visión territorial para impulsar ciudades y territorios más sostenibles, resilientes y habitables.",
  },
  { nombre: "Juan Sierra", rol: "Sistematización de proveedores locales", ubicacion: "", foto: "assets/responsables/juan-sierra.png" },
  {
    nombre: "Juliana Muñoz",
    rol: "Planificación ambiental del territorio y servicios ecosistémicos",
    ubicacion: "",
    foto: "assets/responsables/juliana-munoz.png",
    bio: "Administradora Ambiental y Magíster en Ciencias Ambientales con experiencia en docencia, investigación y planificación ambiental del territorio, específicamente en Planes de Ordenamiento de Cuencas Hidrográficas (POMCAs) y planes de manejo de áreas protegidas. He sido investigadora en escenarios rurales relacionados con la valoración integral de servicios ecosistémicos y la generación de estrategias de adaptación y mitigación al cambio climático desde los sistemas productivos. He acompañado procesos comunitarios en torno a la caracterización del patrimonio natural y cultural y el desarrollo de metodologías de participación social.",
  },
  {
    nombre: "Jenny Velásquez",
    rol: "Evaluación de Daños y Análisis de Necesidades (EDAN)",
    ubicacion: "Cali",
    foto: "assets/responsables/jenny-velazquez.png",
    bio: "Profesional en Administración Ambiental, Especialista en Gerencia Ambiental y Desarrollo Sostenible Empresarial, y Magíster en Energías Renovables. Cuenta con 14 años de experiencia específica en factibilidad ambiental de proyectos del sector eléctrico, con énfasis en la construcción y desarrollo de proyectos con Fuentes No Convencionales de Energía Renovable (FNCER).",
  },
  {
    nombre: "Felipe Chica",
    rol: "Gestión del riesgo de desastres y Eco-Reducción del Riesgo",
    ubicacion: "Pereira",
    foto: "assets/responsables/felipe-chico.png",
    bio: "Administrador ambiental con trayectoria en gestión del riesgo de desastres y Eco-Reducción del Riesgo, desde la política pública hasta la práctica en terreno. He acompañado procesos de fortalecimiento de capacidades comunitarias en varios territorios junto a UNICEF y el Ministerio de Educación donde el enfoque de niñez ha sido esencial para la gestión del riesgo.",
  },
  {
    nombre: "Ryan Howard Therán",
    rol: "Educación ambiental y planificación de la gestión del riesgo",
    ubicacion: "Pereira",
    foto: "assets/responsables/ryan-howard-theran.png",
    bio: "Administrador Ambiental y candidato a Mágister en Gestión del Riesgo de Desastres. Cuento con una trayectoria de 14 años en docencia escolar en niveles de primaria y secundaria, desde donde he impulsado procesos de educación ambiental. Mi trabajo se centra en el acompañamiento e intervención con comunidades, integrando saberes locales con metodologías en procesos de planificación de la gestión del riesgo.",
  },
];
